site_name: ScreamingBedWars
site_url: https://docs.screamingsandals.org/BedWars

theme:
  name: material
  custom_dir: ./overrides
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - content.action.edit
    # - navigation.tabs
  palette:
    - scheme: slate
      primary: teal
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: teal
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScreamingSandals
    - icon: fontawesome/brands/discord
      link: https://screamingsandals.org/discord
  version:
    provider: mike
    default: latest

copyright: Copyright &copy; 2025 ScreamingSandals

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true

edit_uri: "https://github.com/ScreamingSandals/BedWars/blob/docs/0.2.x"
repo_url: https://github.com/ScreamingSandals/BedWars
repo_name: ScreamingSandals/BedWars

plugins:
  - git-revision-date
  - search

nav:
  - Home: index.md
  - Arena creation: arena.md
  - BungeeCord mode: bungee.md
  - Configuration: config.md
  - Language: language.md
  - Commands and Permissions: commands.md
  - Shop: shop.md
  - Upgrades: upgrades.md
  - Placeholder API: placeholderapi.md
  - Special items: specials.md
  - Troubleshooting and FAQ: troubleshooting.md
  - API: api.md