name: Build and publish BedWars master

on:
  push:
    branches: [ master ]
concurrency: bedwars_master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set the Build number
        id: calculated_build_number
        env:
          NUM: ${{ github.run_number }}
        run: echo "build_n=$(($NUM+865))" >> $GITHUB_OUTPUT
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean checkLicenses build publish --stacktrace --warning-mode all
        env:
          NEXUS_URL_RELEASE: ${{ secrets.NEXUS_URL_RELEASE }}
          NEXUS_URL_SNAPSHOT: ${{ secrets.NEXUS_URL_SNAPSHOT }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          BUILD_NUMBER: ${{ steps.calculated_build_number.outputs.build_n }}
      - name: Upload the final artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            plugin/*/build/libs/BedWars*.jar
            !plugin/*/build/libs/BedWars*-unshaded.jar
            protocol/build/libs/BedWars*.jar
            !protocol/build/libs/BedWars*-unshaded.jar
            !plugin/common/**/*
